name: Build Jekyll site and deploy to other repository

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["ioannismavromatis.github.io"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.1"
          bundler-cache: true
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --config _config_ioannis.yml
        env:
          LANG: C.UTF-8
          LANGUAGE: C.UTF-8
          LC_ALL: C.UTF-8
          JEKYLL_ENV: production
      - name: Push a directory to another repository
        uses: ioannismavromatis/copy_folder_to_another_repo_action@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # Source folder from the origin directory
          source_folder: "_site"
          # Destination repository
          destination_repo: "ioannismavromatis/ioannismavromatis.github.io"
          # Email for the git commit
          user_email: "ioan.mavromatis@gmail.com"
          # GitHub username for the commit
          user_name: "ioannismavromatis"
          # branch to push folder to, defaults to master
          destination_branch: "master"
          # The commit message
          commit_msg: "Updating website after commit at ioannismavromatis/al-folio@${{ github.sha::6 }}"

  # # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
